"""
Generate the committed probe extract the firing line fires.

The panel needs the shipped battery's input-stage payloads in the browser. It cannot
read them at runtime: `GET /redteam/runs` requires an administrator or devops role and
the guardrails screen lives only in the `ai_team` portal, whose principals are
tenant-pinned — so every reader of that screen is refused the payloads, and in a fresh
environment there is no stored run to refuse them from.

So the payloads are extracted from `aegis.redteam.battery.ATTACK_BATTERY` — the same
constant the runner fires — and committed. They are the battery's own payloads, not a
sample of one run and not written for the demo. Re-run this after editing the battery:

    PYTHONPATH=aegis/src backend/.venv/bin/python scripts/gen-battery-probes.py

The verdicts remain live: nothing about the outcome is committed, only the payloads.
"""

from __future__ import annotations

import json
import pathlib

from aegis.redteam.battery import ATTACK_BATTERY

OUT = pathlib.Path("web/src/components/guardrail/batteryProbes.ts")


def _value(field: object) -> str:
    """`Stage.INPUT` and `Category.JAILBREAK` are enums; the wire wants their values."""
    return str(getattr(field, "value", field))


def main() -> None:
    probes = [
        {
            "id": a.id,
            "prompt": a.prompt,
            "category": _value(a.category),
            "owasp": _value(a.owasp),
            # A burst probe's `prompt` is one query of a sequence, so firing it alone
            # would misrepresent it. The stage filter already excludes the sequence
            # stage; this guards a burst that is ever added to the input stage.
            "benign": _value(a.category) == "benign_control",
        }
        for a in ATTACK_BATTERY
        if _value(a.stage) == "input" and not a.burst
    ]

    body = json.dumps(probes, indent=2, ensure_ascii=False)
    OUT.write_text(
        "// GENERATED by scripts/gen-battery-probes.py — do not edit by hand.\n"
        "//\n"
        "// The input-stage payloads of the shipped red-team battery\n"
        "// (`aegis.redteam.battery.ATTACK_BATTERY`), extracted so the firing line can\n"
        "// fire them without a stored run and without a role the guardrails screen's\n"
        "// own principals do not hold. Payloads only — every verdict is measured live.\n"
        "\n"
        "export interface BatteryProbe {\n"
        "  id: string\n"
        "  prompt: string\n"
        "  category: string\n"
        "  owasp: string\n"
        "  /** A control that ought to pass. Kept, because a rail that only ever blocks\n"
        "   *  has not been shown to discriminate. */\n"
        "  benign: boolean\n"
        "}\n"
        "\n"
        f"export const BATTERY_PROBES: readonly BatteryProbe[] = {body}\n",
        encoding="utf-8",
    )
    kinds = sorted({p["category"] for p in probes})
    print(f"wrote {OUT} — {len(probes)} probes, {len(kinds)} categories")


if __name__ == "__main__":
    main()
